branches:
  only:
  - master
  - release15
language: cpp
sudo: required
env:
  - TARGET_OS=debian
matrix:
  include:
    os: osx
    env: TARGET_OS=macos
    env: QT_VERSION=5.7.1
services: docker
addons:
  apt:
    packages:
      - libc6-i386
      - icnsutils
      - graphicsmagick
cache:
  directories:
  - "$HOME/gcc-arm-none-eabi-5_2-2015q4"
  - package/$TARGET_OS/mono_framework
  - package/$TARGET_OS/monoprog
  - package/$TARGET_OS/little-helper
compiler:
  - gcc
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq qt5-default qttools5-dev-tools devscripts libusb-1.0-0-dev libudev-dev libqt5serialport5-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; echo "Using Qt $QT_VERSION"; then export PATH=$PATH:/usr/local/Cellar/qt5/$QT_VERSION/bin; fi
  - qmake -version
install:
  - export GCC_DIR=$HOME/gcc-arm-none-eabi-5_2-2015q4
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export GCC_ARCHIVE=$HOME/gcc-arm-none-eabi-5_2-2015q4-20151219-linux.tar.bz2; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export GCC_URL=https://launchpad.net/gcc-arm-embedded/5.0/5-2015-q4-major/+download/gcc-arm-none-eabi-5_2-2015q4-20151219-linux.tar.bz2; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export GCC_ARCHIVE=$HOME/gcc-arm-none-eabi-5_2-2015q4-20151219-mac.tar.bz2; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export GCC_URL=https://launchpad.net/gcc-arm-embedded/5.0/5-2015-q4-major/+download/gcc-arm-none-eabi-5_2-2015q4-20151219-mac.tar.bz2; fi
  - if [ ! -e $GCC_DIR/bin/arm-none-eabi-g++ ]; then wget $GCC_URL -O $GCC_ARCHIVE; tar xfvj $GCC_ARCHIVE -C $HOME; fi
  - export PATH=$PATH:$GCC_DIR/bin
script:
  - echo Building on $TRAVIS_OS_NAME...
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd package/debian; bash build.sh -ci; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd package/macos; bash osx_build.sh -ci; fi
notifications:
  email: false
  slack:
    on_success: change
    rooms:
      secure: YPbjrWKWuGYzhKu2rv6VB0+MbHz/IFMd0F+TKeNkjjxm2GD6+u2Oruld6hxa11YnnnNjDvQRY7BFhWiM2Ib2Dmu3GlrH9qALx65vBKwoKaWBXtZg3dL3xSGdHzmVs9coDg2yummsx8c8ka++xv3nw73nsUn2jIZxoZt0Q2ZUABrk061yqdG763xykgAM29X7kUhhX3IAE4teT6y0NxuLjk4QwM/pqmpO7qego+hVWUttsbNnevZHkO6CmtGUarJSm2Tjm4LnKWiMyNR8xqK2YcjJE2ldYNEwUZfdXwcBAw+7HIo6dnc/rIsGFILG1mGwKamwodLpdGbeje2YJQlhhsSYR1hUMT2NgjfUfGIK1f/A2GnFrqDwLiluXgl+RlntVS5gMEqFIbQPY+cJ0YIzKj3x37riaS5BMNxTUpQdI0rUiyUqS1iZBb5UyFkDtf8+H+bOHE6tWfY5cmsN0TsQpMBBTisxfhSyUmB/EJk7TTYiomeCrNshmwIdr8EocvMM2hv7myrm+mcekWKYt+cvHhVSz3JMPspWcO+RrNcr3XR1ooz8gE6oX6aiBhX38n3L0D57mYFxfvaSywV7CM2vattuV2CjNwua2qfHfnkq0YN4pfNA675acn/JHpdA4I7fX644fTI1t5iErPNNFMDD6sm5gVVXFymWFoqeu0lRi48=
# deploy:
#   provider: bintray
#   file:
#   user: stoffera
#   key:
#     secure: rvvmQuua/DB73hwr8umLGv/5RQHMEylQTGvm9WzyszmCNr/to3nJz6e27LuLFsRxcQ6z+sQQIHveCHRixn6QFOFV3KoWMm6jBcigBchOgvd96z8tUMAdWGEymOFJQFwpG9rzZc7dJsQgA+KE1d03KnVJYVw6fvO+a1oEgydI0zZkVsSOPIt9RCG80lwwaGMU2lA3m549wFTBj5PbHRDaZDOOC8YIEJ9z8iELn4iFezoioaOg6sCbf/8+w93+WkSdXXFrtGfsv4F7gVZZPME+2B2ST5Z8JHdhwCxLKvUzaqHGXza7lfZ5iCCO4JAcmN+P4UrBIdTHoFXc5nXC9BgaGUmfz27AATd4nkdsDKFFTqSEdrRfhP1F2UNZ5xXSFnlvu5VMexddd0LZNsISGOuPl6HlOZRvHAwHyaSd/wUh1RINZwvm3+4+yOznT+o8PIvofVuUf6C3tmAMy+WD5bCSOyXRTDkc3aaK81Qjg/U78bSfki+ZOiiEdy+Ai3s6eIWIrXfvCOusikySim1Ql/N+UVUFzYwXGk9iNOfke8rHfCLDcGQHDozksbhaJf4gb75oK4UbFg+g0zCZO28+SU2GYbLx88HvH4Nj2HZioQ/uQyLGit9x4DqhEZfb3QjRwjCT6sgCqhZVvCXjOchNcg9/+0YQze9lwXwTmggM4+M6N24=
