branches:
  only:
  - master
  - production
language: cpp
matrix:
  include:
  - os: linux
    sudo: required
    dist: trusty
    env: TARGET_OS=debian
    services: docker
  - os: osx
    env:
    - TARGET_OS=macos
    - QT_VERSION=5.7.1
    - QT_DIR=qt@5.7
cache:
  directories:
  - "$HOME/gcc-arm-none-eabi-5_2-2015q4"
  - package/$TARGET_OS/monoprog
  - package/$TARGET_OS/little-helper
compiler:
- gcc
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt@5.7 && export PATH=$PATH:/usr/local/Cellar/$QT_DIR/$QT_VERSION/bin;
  fi
- qmake -version
install:
- export GCC_DIR=$HOME/gcc-arm-none-eabi-5_2-2015q4
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export GCC_ARCHIVE=$HOME/gcc-arm-none-eabi-5_2-2015q4-20151219-mac.tar.bz2;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export GCC_URL=https://launchpad.net/gcc-arm-embedded/5.0/5-2015-q4-major/+download/gcc-arm-none-eabi-5_2-2015q4-20151219-mac.tar.bz2;
  fi
- if [ "$TRAVIS_OS_NAME" == "osx" -a ! -e $GCC_DIR/bin/arm-none-eabi-g++ ]; then wget
  $GCC_URL -O $GCC_ARCHIVE; tar xfvj $GCC_ARCHIVE -C $HOME; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$PATH:$GCC_DIR/bin; fi
script:
- echo Building on $TRAVIS_OS_NAME...
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd package/debian; mkdir dist && bash ci_build.sh `pwd`/dist $TRAVIS_BRANCH $TRAVIS_BRANCH; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd package/macos; FRM_BRANCH=$TRAVIS_BRANCH; bash osx_build.sh -ci;
  fi
notifications:
  email: false
  slack:
    on_success: change
    rooms:
      secure: YPbjrWKWuGYzhKu2rv6VB0+MbHz/IFMd0F+TKeNkjjxm2GD6+u2Oruld6hxa11YnnnNjDvQRY7BFhWiM2Ib2Dmu3GlrH9qALx65vBKwoKaWBXtZg3dL3xSGdHzmVs9coDg2yummsx8c8ka++xv3nw73nsUn2jIZxoZt0Q2ZUABrk061yqdG763xykgAM29X7kUhhX3IAE4teT6y0NxuLjk4QwM/pqmpO7qego+hVWUttsbNnevZHkO6CmtGUarJSm2Tjm4LnKWiMyNR8xqK2YcjJE2ldYNEwUZfdXwcBAw+7HIo6dnc/rIsGFILG1mGwKamwodLpdGbeje2YJQlhhsSYR1hUMT2NgjfUfGIK1f/A2GnFrqDwLiluXgl+RlntVS5gMEqFIbQPY+cJ0YIzKj3x37riaS5BMNxTUpQdI0rUiyUqS1iZBb5UyFkDtf8+H+bOHE6tWfY5cmsN0TsQpMBBTisxfhSyUmB/EJk7TTYiomeCrNshmwIdr8EocvMM2hv7myrm+mcekWKYt+cvHhVSz3JMPspWcO+RrNcr3XR1ooz8gE6oX6aiBhX38n3L0D57mYFxfvaSywV7CM2vattuV2CjNwua2qfHfnkq0YN4pfNA675acn/JHpdA4I7fX644fTI1t5iErPNNFMDD6sm5gVVXFymWFoqeu0lRi48=
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: cKv6YVoh3xxOlrM2jAE0uCrRylZnOCo36roQiQ/XPthxBslwZ8ssRuCYI3hX4qindHT12bSwX1ZJe+Z/Io0Jc0oPLwvEVYJwIHnbj9evAUaHTe29TeMZXU7oV0hgBr4o22uANU2ii1MYnUGv0oYNaEDiXIb5V8NBCK/ArsKH6qsQeQ6FXas1HJxeTihLRPxq6G0JAko8CCAs+P3dWX2jMgba5UiUyo3mA6mljAeqxE1G8dO3dbodyoFTDxqSeJI/meNkkFk5RA1dMptlc+9cuuJmybVRGGwY7+L8i67U/AE/2GhJU0F4xKtHFZqtpSflerAlDubX4w4xRW4oFB01DP7tgtvLCYr6QAnig17BFf5dRqDgloJvX/wx9DGduoPf7GvW2e6prPXabTgVDVHtua3wBXpw9js02Ob60V0kr+OtTTHoTuBbWmcRKBilEP7gBWNZNUvGMJu8J1pRq81HVxdZ/MiIHc61Vj1J4P5VLdMnWSFevJlPpG4hlnwRoZaNIQCn4G9uNBGFtdpLUloe97Vi7L6dKyl6/ozGFYTR4/Wc1YbxBsuK435fGiuLZ+3tIAsIvL5jF6R0Ms1/0XfmjEDyc1N6oL/Jteh/JywppgvrOB8kIJtxRu7rqOPqiAhTdyi6LgM2K0NlVWmrAL2M7HSp9khg0sJrIyVu4CX/m68=
  file: package/debian/dist/*
  on:
    repo: getopenmono/openmono_package
    branch: production
