version: 1.4.{build}
branches:
  only:
  - master
  - appveyor
image: Visual Studio 2013
platform: x86
environment:
  certSecret:
    secure: O214GWTK6/ICym59dN06YykFoZbWimFdewARqyW83V0=
install:
    - nuget install secure-file -ExcludeVersion
    - secure-file\tools\secure-file -decrypt package\win\monolit-cert.p12.enc -secret %certSecret% -out package\win\monolit-cert.p12
cache:
- package/win/gcc-arm-none-eabi-5_2-2015q4-20151219-win32
- package/win/mono_framework
- package/win/monoprog
build_script:
- cmd: >-
    cd package/win

    set PATH=%PATH%;C:\MinGW\bin;C:\MinGW\msys\1.0\bin;C:\Qt\5.5\msvc2013\bin

    bash win_build.sh -ci
artifacts:
- path: package/win/OpenMonoSetup-v*.exe
  name: OpenMonoSetup
- path: package/win/OpenMonoSDK-v*.zip
  name: OpenMonoZip