version: 1.7.{build}
branches:
  only:
  - master
  - production
image: Visual Studio 2013
platform: x86
environment:
    my_secret:
        secure: Qvyeh+GUyX4YnohD43RSOw==
install:
    - nuget install secure-file -ExcludeVersion
    - secure-file\tools\secure-file -decrypt package\win\monolit-cert.p12.enc -secret %my_secret% -out package\win\monolit-cert.p12
cache:
- package/win/gcc-arm-none-eabi-5_2-2015q4-20151219-win32
- package/win/monoprog
build_script:
- cmd: >-
    cd package/win

    set PATH=%PATH%;C:\MinGW\bin;C:\MinGW\msys\1.0\bin;C:\Qt\5.7\msvc2013\bin

    bash win_build.sh -ci
artifacts:
- path: package/win/OpenMonoSetup-v*.exe
  name: OpenMonoSetup
- path: package/win/OpenMonoSDK-v*.zip
  name: OpenMonoZip
- path: package/win/OpenMonoSetup-v*.exe.sha1
  name: OpenMonoSetupHash